#!/usr/bin/env python3
"""
gen_font.py - rasterize DejaVu Sans TrueType glyphs (ASCII 32-126) into
8bpp anti-aliased coverage bitmaps and emit a C header (font_data.h) for
direct compositing onto a UEFI GOP framebuffer.

DejaVu fonts are covered by the Bitstream Vera / DejaVu license, which
explicitly permits embedding, modifying and redistributing the font
(including as rasterized bitmap derivatives) in software - see
https://dejavu-fonts.github.io/License.html
"""

import sys
from PIL import ImageFont

FIRST_CHAR = 32
LAST_CHAR = 126  # inclusive
NUM_CHARS = LAST_CHAR - FIRST_CHAR + 1

FACES = [
    # (c_name, ttf_path, px_size)
    ("FONT_SMALL",   "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",      13),
    ("FONT_BODY",    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",      17),
    ("FONT_HEADING", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 23),
    ("FONT_TITLE",   "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 32),
]


def rasterize_face(ttf_path, px_size):
    font = ImageFont.truetype(ttf_path, px_size)
    ascent, descent = font.getmetrics()
    glyphs = []
    blob = bytearray()

    for code in range(FIRST_CHAR, LAST_CHAR + 1):
        ch = chr(code)
        bbox = font.getbbox(ch, anchor="la")  # (left, top, right, bottom)
        advance = int(round(font.getlength(ch)))

        if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            # space or empty glyph
            glyphs.append((0, 0, 0, 0, advance, len(blob)))
            continue

        left, top, right, bottom = bbox
        w, h = right - left, bottom - top
        mask = font.getmask(ch, mode="L")  # rendered at (0,0)=left-ascender

        data_offset = len(blob)
        mw, mh = mask.size
        for y in range(top, bottom):
            my = y - top
            for x in range(left, right):
                mx = x - left
                px = mask.getpixel((mx, my)) if (0 <= mx < mw and 0 <= my < mh) else 0
                blob.append(px)

        glyphs.append((w, h, left, top, advance, data_offset))

    return {
        "ascent": ascent,
        "descent": descent,
        "line_height": ascent + descent,
        "glyphs": glyphs,
        "blob": bytes(blob),
    }


def emit_c(faces_data, out_path):
    lines = []
    lines.append("/* Auto-generated by gen_font.py from DejaVu Sans (Bitstream Vera / DejaVu")
    lines.append(" * license - embedding and redistribution explicitly permitted). */")
    lines.append("#ifndef FONT_DATA_H")
    lines.append("#define FONT_DATA_H")
    lines.append("")
    lines.append("#define FONT_FIRST_CHAR %d" % FIRST_CHAR)
    lines.append("#define FONT_LAST_CHAR %d" % LAST_CHAR)
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    UINT8 w, h;")
    lines.append("    INT8 xoff, yoff;")
    lines.append("    UINT8 advance;")
    lines.append("    UINT32 dataOffset;")
    lines.append("} GLYPH_INFO;")
    lines.append("")
    lines.append("typedef struct {")
    lines.append("    UINT8 ascent, lineHeight;")
    lines.append("    CONST GLYPH_INFO *glyphs;")
    lines.append("    CONST UINT8 *data;")
    lines.append("} FONT_FACE;")
    lines.append("")

    for c_name, face in faces_data.items():
        glyphs = face["glyphs"]
        blob = face["blob"]

        lines.append("static const GLYPH_INFO %s_GLYPHS[] = {" % c_name)
        for (w, h, xoff, yoff, advance, off) in glyphs:
            lines.append("    {%d,%d,%d,%d,%d,%dU}," % (w, h, xoff, yoff, advance, off))
        lines.append("};")
        lines.append("")

        lines.append("static const UINT8 %s_DATA[] = {" % c_name)
        row = []
        for i, b in enumerate(blob):
            row.append(str(b))
            if len(row) == 32:
                lines.append("    " + ",".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ",".join(row) + ",")
        if not blob:
            lines.append("    0,")
        lines.append("};")
        lines.append("")

        lines.append("static const FONT_FACE %s = { %d, %d, %s_GLYPHS, %s_DATA };" %
                      (c_name, face["ascent"], face["line_height"], c_name, c_name))
        lines.append("")

    lines.append("#endif /* FONT_DATA_H */")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    faces_data = {}
    total_bytes = 0
    for c_name, ttf_path, px_size in FACES:
        face = rasterize_face(ttf_path, px_size)
        faces_data[c_name] = face
        total_bytes += len(face["blob"])
        print("  %-14s %2dpx  ascent=%d lineHeight=%d  %d glyph bytes" %
              (c_name, px_size, face["ascent"], face["line_height"], len(face["blob"])),
              file=sys.stderr)

    out_path = sys.argv[1] if len(sys.argv) > 1 else "font_data.h"
    emit_c(faces_data, out_path)
    print("Total glyph bitmap data: %d bytes -> %s" % (total_bytes, out_path), file=sys.stderr)


if __name__ == "__main__":
    main()
